version: '2'

services:
    movie-recommender:
        image: 192.168.1.151:32000/movie-recommender:1.0.13
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: unless-stopped
