tables:
  movie_ratings:
    - column_type: "int"
      db_column: "userId"
      isnull: "NOT NULL"
    - column_type: "int"
      db_column: "movieId"
      isnull: "NOT NULL"
    - column_type: "float"
      db_column: "rating"
      isnull: "NOT NULL"
    - column_type: "TIMESTAMPTZ"
      db_column: "timestamp"
      isnull: "NOT NULL"
    - column_type: "primary"
      db_column: "(userId,movieId)"
      isnull: "NOT NULL"
  movies:
    - column_type: "int"
      db_column: "movieId"
      isnull: "NOT NULL"
    - column_type: "VARCHAR"
      db_column: "title"
      isnull: "NOT NULL"
    - column_type: "VARCHAR"
      db_column: "genre"
      isnull: "NULL"
    - column_type: "primary"
      db_column: "(movieId)"
      isnull: "NOT NULL"
  link:
    - column_type: "int"
      db_column: "movieId"
      isnull: "NOT NULL"
    - column_type: "int"
      db_column: "tmdbId"
      isnull: "NOT NULL"
    - column_type: "VARCHAR"
      db_column: "imdbId"
      isnull: "NOT NULL"
    - column_type: "primary"
      db_column: "(movieId,tmdbId)"
      isnull: "NOT NULL"