apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: leenet-gateway-{{ .Values.dnsName }}
  namespace: {{ .Values.gatewayNamespace }}
spec:
  gateways:
    - {{ .Values.gateway }}
  hosts:
    - {{ .Values.dnsName }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "movie-recommender.fullname" . }}.{{ .Values.appNamespace }}.svc.cluster.local
            port:
              number: 2361
